### ISSUE TITLE
Kingfisher archive issues

### ISSUE THREAD

**Issue by MartinW** [EnesKaraosman/SwiftyChat#13]
Kingfisher issues when attempting build/archive for arm64 device
```
Cannot find type 'Binding' in scope
Cannot find type 'Image' in scope
Cannot find type 'View' in scope
```

Xcode 13.0, building for iOS 13. 
Runs OK on the simulator.
Reproducible with SwiftyChatExample project.

Is this a config issue? 

Thanks
Martin

**Comment by owais-applligent** [comment]
I am also facing this issue when archiving after updating Xcode to 13. But it still working properly in Xcode 12.

**Comment by MartinW** [comment]
@EnesKaraosman Thanks for this project and thanks for this update 👍🏻
